VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64-daily"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box_check_update = true

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network 'private_network', ip: '192.168.3.3'
  
  config.vm.provider :virtualbox do |vb|
	vb.name = "rspp"
    vb.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
    vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # Uncomment next line to enable GUI for the virtual machine
    # vb.gui = true
  end

  config.vm.provision :shell do |shell|
    shell.inline = "
      if [ ! -d /etc/puppet/modules/apache ]; then
        puppet module install puppetlabs-apache
      fi
      if [ ! -d /etc/puppet/modules/mysql ]; then
        puppet module install puppetlabs-mysql
      fi
      if [ ! -d /etc/puppet/modules/apt ]; then
        puppet module install puppetlabs-apt
      fi
      if [ ! -d /etc/puppet/modules/ruby ]; then
        puppet module install puppetlabs-ruby
      fi
      if [ ! -d /etc/puppet/modules/nodejs ]; then
        puppet module install puppetlabs-nodejs
      fi
      "
  end
  config.vm.synced_folder 'C:\Users\dimasik\ucheba\PriceCalculationOfCircuitBoards\project', '/var/www', create: true
  config.vm.provision :shell do |shell|
    shell.inline = " php5enmod mcrypt
    cd /var/www/rspp/app
    sudo php -r \"readfile('https://getcomposer.org/installer');\" | php
    sudo php composer.phar update
    bower update
    npm install --no-bin-links
    grunt built
    grunt compile_translate
    grunt built_translate
    cd cd /var/www/rspp/app/server
    sudo php yii migrate/down all
    sudo php yii migrate
    "
  config.vm.provision "puppet"


  end


end
