VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/utopic64'
  config.vm.box_url =
      'https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-i386-vagrant-disk1.box'

  config.vm.network 'private_network', ip: '192.168.4.4'
  
  config.vm.provider :virtualbox do |vb|
  vb.name = 'PriceCalculationOfCircuitBoards'
    vb.customize ['modifyvm', :id, '--ostype', 'Ubuntu_64']
    vb.customize ['modifyvm', :id, '--memory', 512]
    vb.customize ['modifyvm', :id, '--cpus', "1"]
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    # Uncomment next line to enable GUI for the virtual machine
    # vb.gui = true
  end

  config.vm.synced_folder '.', '/vagrant', mount_options: ["dmode=777","fmode=666"]

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.provision :shell do |shell|
    shell.path = 'provision/setup.sh'
  end
end
