<?php  //[STAMP] 100b124d8b28ea87d60291c2aec7eac3
namespace tests\codeception\common\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile



trait UnitTesterActions
{
   
}