name          'mhuffnagle-curl'
version       '0.0.2'
source        'https://github.com/Element84/puppet-curl.git'
author        'element84'
license       'Apache License, Version 2.0'
summary       'Installs curl'
description   'A simple module for installing curl'
project_page  'https://github.com/Element84/puppet-curl'
